### ISSUE TITLE
Pull data from zenodo

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits#15]
Once the dataset is public, we'll want a function that can pull the data directly from the Austraits page on Zenodo: https://doi.org/10.5281/zenodo.3568417

On Zenodo each release has a doi. There's also an overall "concept doi", which is pointer to the entire project (and by default redirects to the latest release).

![image](https://user-images.githubusercontent.com/3589590/123200766-bd6bcf00-d4f4-11eb-8dd0-6c625690e0c3.jpeg)

For any given version, we can access a json of the metadata via a link like https://zenodo.org/api/records/4316550, where the number 4316550 comes form the doi: 10.5281/zenodo.4316550

Using this we can load the metadata straight into R
```r
x <- 
  jsonlite::fromJSON("https://zenodo.org/api/records/4316550")
# or  
# httr::GET("https://zenodo.org/api/records/4316550") |> httr::content(as = "text") |> fromJSON()
```

This information includes links to the files, which we can use to download the file
```r
url <- x$files$links$download[1]
filename <- basename( x$files$filename[1] )
download.file(url, filename)
```

So that will work for retrieving

* the latest version, whatever it is
* any version when you know the DOI

A remaining challenge is to discover all the versions associated with the conceptdoi. So far I can't see how to do that from zenodo. But it is possible via doi resolution service.

**Comment by dfalster** [comment]
We can potentially access info on all version using Using DOI content negotiation:

 
```
$ curl -LH "Accept: application/vnd.datacite.datacite+xml" https://doi.org/10.5281/zenodo.3568417
```
 
```
<?xml version="1.0" encoding="UTF-8"?>

<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">

    <identifier identifierType="DOI">10.5281/ZENODO.3568417</identifier>

… various stuff …

    <relatedIdentifiers>

        <relatedIdentifier relatedIdentifierType="URL" relationType="IsCompiledBy" resourceTypeGeneral="Dataset">https://github.com/traitecoevo/austraits.build/tree/v0.9.1</relatedIdentifier>

        <relatedIdentifier relatedIdentifierType="DOI" relationType="IsCitedBy" resourceTypeGeneral="Text">10.1101/2021.01.04.425314</relatedIdentifier>

        <relatedIdentifier relatedIdentifierType="DOI" relationType="IsPartOf" resourceTypeGeneral="Text">10.1101/2021.01.04.425314</relatedIdentifier>

        <relatedIdentifier relatedIdentifierType="DOI" relationType="HasVersion">10.5281/zenodo.3568418</relatedIdentifier>

        <relatedIdentifier relatedIdentifierType="DOI" relationType="HasVersion">10.5281/zenodo.3568429</relatedIdentifier>

        <relatedIdentifier relatedIdentifierType="DOI" relationType="HasVersion">10.5281/zenodo.3583418</relatedIdentifier>

        <relatedIdentifier relatedIdentifierType="DOI" relationType="HasVersion">10.5281/zenodo.4316516</relatedIdentifier>

        <relatedIdentifier relatedIdentifierType="DOI" relationType="HasVersion">10.5281/zenodo.4316550</relatedIdentifier>

        <relatedIdentifier relatedIdentifierType="URL" relationType="IsPartOf">https://zenodo.org/communities/austraits</relatedIdentifier>

    </relatedIdentifiers>

… various stuff …

</resource>
```

Reading directly into R -> 

```
> httr::GET("https://doi.org/10.5281/zenodo.3568417", add_headers(Accept = "application/vnd.datacite.datacite+xml")) -> x
> rawToChar(x$content) %>% xml2::read_xml() -> y
> as_list(y) -> z
> z$resource$relatedIdentifiers[[4]]
[[1]]
[1] "10.5281/zenodo.3568418"

attr(,"relatedIdentifierType")
[1] "DOI"
attr(,"relationType")
[1] "HasVersion"
```

**Comment by dfalster** [comment]
Other useful info - Zenodo API https://developers.zenodo.org/#deposition-files

Checkout how other packages retrieve data, e.g:

- eg raster: https://github.com/rspatial/raster/blob/master/R/getData.R#L8

**Comment by fontikar** [comment]
Doesn't exactly load all the different version of austraits but load_austraits (0ca239a) downloads 2.1.0 and adds into data/

**Comment by jrfep** [comment]
There is a function in zen4R package to [get the different versions](https://www.rdocumentation.org/packages/zen4R/versions/0.5/topics/get_versions) :
```
> require(zen4R)
> get_versions('10.5281/zenodo.3568417')
        date version                    doi
1 2020-07-08  v2.0.0 10.5281/zenodo.4316516
2 2020-12-11  v2.1.0 10.5281/zenodo.4316550
3 2021-07-14  v3.0.0 10.5281/zenodo.5099545
4 2021-07-14  v3.0.1 10.5281/zenodo.5099552
5 2021-07-14  v3.0.2 10.5281/zenodo.5112001
```

**Comment by dfalster** [comment]
Thanks so much Jose for this great suggestion!  I had a tentative method in mind, but it wasn't going to retrieve the version numbers. Using this function from zen4R will be much better!

the zen4R package may offer other useful features too, as it offers a proper interface to the zenodo API.

**Comment by fontikar** [comment]
I'm not sure what is the best way to integrate `zen4R` in `austraits` as it is not on CRAN for me to import functions from! Do you have any advice @jrfep? Thank you in advance! I will investigate :)

**Comment by dfalster** [comment]
I'm confused. https://cran.r-project.org/web/packages/zen4R/index.html

**Comment by fontikar** [comment]
OH!!! Would you look at that! That is so strange! Why would they recommend folks to download from github and not CRAN on their page. Ignore!

**Comment by fontikar** [comment]
Strange that my version of `get_versions` produces a different outpu than @jrfep (without the version number!) 
```library(zen4R)
> get_versions('10.5281/zenodo.3568417') 
              created       date version                    doi
1 2019-12-09 23:13:04 2019-12-09       1 10.5281/zenodo.3568418
2 2019-12-10 00:15:52 2019-12-09       2 10.5281/zenodo.3568429
3 2019-12-19 03:48:40 2019-12-09       3 10.5281/zenodo.3583418
4 2020-12-11 08:38:30 2020-07-08       4 10.5281/zenodo.4316516
5 2020-12-11 08:43:46 2020-12-11       5 10.5281/zenodo.4316550
6 2021-07-14 01:14:53 2021-07-14       6 10.5281/zenodo.5099545
7 2021-07-14 01:25:41 2021-07-14       7 10.5281/zenodo.5099552
8 2021-07-18 06:32:30 2021-07-14       8 10.5281/zenodo.5112001``` 

@jrfep do you have a token for the Zenodo API?

**Comment by dfalster** [comment]
Using CRAN version, I also get 8 recors

```
> zen4R::get_versions('10.5281/zenodo.3568417')
              created       date version                    doi
1 2019-12-09 23:13:04 2019-12-09       1 10.5281/zenodo.3568418
2 2019-12-10 00:15:52 2019-12-09       2 10.5281/zenodo.3568429
3 2019-12-19 03:48:40 2019-12-09       3 10.5281/zenodo.3583418
4 2020-12-11 08:38:30 2020-07-08       4 10.5281/zenodo.4316516
5 2020-12-11 08:43:46 2020-12-11       5 10.5281/zenodo.4316550
6 2021-07-14 01:14:53 2021-07-14       6 10.5281/zenodo.5099545
7 2021-07-14 01:25:41 2021-07-14       7 10.5281/zenodo.5099552
8 2021-07-18 06:32:30 2021-07-14       8 10.5281/zenodo.5112001
```

**Comment by dfalster** [comment]
And BTW - there are 8 versions available on zenodo. I tried installing off GitHub and same result.

Something I really like about the previous results were that they included the version numbers, i.e.`1.0.1`, `2.0.0`, `2.0.1` etc

I thought hat would be useful. But maybe we just need to run everything via DOI

**Comment by fontikar** [comment]
Agreed! I thought that was the most useful! My plan to to save the `get_versions()` output as exported data with the package (or maybe keep it internal). I've lodged an issue with zen4R and for now just edited the version number and added our own ones!

**Comment by dfalster** [comment]
Actually, we want the ability to update output of `get_versions` so I wouldn't store as package content. What if someone releases a new version on zenodo? The user wouldn't know about it, as they'd be using an out of date list.

happy to discuss today if that's helpful

**Comment by fontikar** [comment]
Ah yes I understand! I will import the function from the CRAN package then :) hopefully will have a tester version for you tomorrow! 🤞

**Comment by jrfep** [comment]
hm, looks like a change between versions of zen4R package... my current version also shows the same output now with 8 version but without the version names.

Alternatively, you could also read the json file from the API directly:
```
require(jsonlite)

res <- read_json("https://zenodo.org/api/records/?q=title:Austraits&all_versions=true")

sapply(res$hits$hits,function(x) 
  data.frame(doi=x$metadata$doi,
             version=x$metadata$version,
             date=x$metadata$publication_date), simplify=T)
```
That should give you this output:

```
       [,1]                     [,2]                    
doi     "10.5281/zenodo.4316550" "10.5281/zenodo.5099545"
version "v2.1.0"                 "v3.0.0"                
date    "2020-12-11"             "2021-07-14"            
        [,3]                     [,4]                    
doi     "10.5281/zenodo.5112001" "10.5281/zenodo.5099552"
version "v3.0.2"                 "v3.0.1"                
date    "2021-07-14"             "2021-07-14"            
        [,5]                     [,6]                    
doi     "10.5281/zenodo.4316516" "10.5281/zenodo.3583418"
version "v2.0.0"                 "v0.9.1"                
date    "2020-07-08"             "2019-12-09"            
        [,7]                     [,8]                    
doi     "10.5281/zenodo.3568429" "10.5281/zenodo.3568418"
version "v0.9.0"                 "v0.1.0"                
date    "2019-12-09"             "2019-12-09"  
```

**Comment by dfalster** [comment]
Great suggestion @jrfep.

@fontikar - better to read the json file directly, as Jose suggests. We can then skip dependency on zen4r

In the request to API, we can used the concept record id (`conceptrecid`) rather than `title`:

```
 res <- read_json("https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true")

sapply(res$hits$hits,function(x) 
  data.frame(doi=x$metadata$doi,
             version=x$metadata$version,
             date=x$metadata$publication_date), simplify=T)

        [,1]                     [,2]                     [,3]                     [,4]                     [,5]                     [,6]                     [,7]
doi     "10.5281/zenodo.4316550" "10.5281/zenodo.5099545" "10.5281/zenodo.5112001" "10.5281/zenodo.5099552" "10.5281/zenodo.4316516" "10.5281/zenodo.3583418" "10.5281/zenodo.3568429"
version "v2.1.0"                 "v3.0.0"                 "v3.0.2"                 "v3.0.1"                 "v2.0.0"                 "v0.9.1"                 "v0.9.0"
date    "2020-12-11"             "2021-07-14"             "2021-07-14"             "2021-07-14"             "2020-07-08"             "2019-12-09"             "2019-12-09"
        [,8]
doi     "10.5281/zenodo.3568418"
version "v0.1.0"
date    "2019-12-09"
```

**Comment by dfalster** [comment]
Also, here is documentation for the Zotero API: https://developers.zenodo.org/#records

**Comment by fontikar** [comment]
I think I need a little clarification @dfalster! 🙋‍♀️ 

Will `load_austraits` be saving 2 different json? 
1) json containing versioning details + dois
2) json for a specific version of austraits that the user wants to load?

**Comment by dfalster** [comment]
Assuming it contains the right info (licenses, file links, citation) I was thinking we'd we replace the current json with the new one contains versioning details + dois. 

Otherwise could save both. See what works.
