### ISSUE TITLE
rename package

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits#2]
Hi @fontikar 

I'd like to rename the package to `austraits`. There's three steps to this

1. Change name of GitHub repo  (see https://github.community/t/how-to-do-i-rename-my-repo/281)
2. Change package name in code
3. Update the name within the file .git/config` in your local copy of the repo

Can you do this as soon as comfortably possible?

**Comment by roblanf** [comment]
I know I am just a really annoying early adopter here, so with apologies, and the obvious caveat that maybe I'm just being really dumb.

If I do this:

```
install.packages("remotes")
remotes::install_github("traitecoevo/austraits")
```

I can now load `austraits.R`, but not `austraits`. 

```
> library(austraits.R)
> library(austraits)
Error in library(austraits) : there is no package called ‘austraits’
```

**Comment by fontikar** [comment]
Hey Rob! Thanks for testing this out! I'm on it! Changing a package name is a lot harder than I thought!

**Comment by fontikar** [comment]
I know suspect its because I never completed the pull request and merged all the new name-change related changes to master branch, doing this now!

**Comment by fontikar** [comment]
Hey Rob! Thanks again for tuning in! I just merged the name change commits into master.
Just tried the following code in a new Rstudio window and it seems to be installing okay! Let me know how you go! 
`remotes::install_github("traitecoevo/austraits")
library(austraits)`


![Screen Shot 2021-06-02 at 2 34 12 pm](https://user-images.githubusercontent.com/12161802/120424460-bfd48080-c3af-11eb-8c2e-106978df456f.png)
