### ISSUE TITLE
Helpful warning messages in functions

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#23]
E.g. pivot_ requires austraits$traits but if user supplies austraits only perhaps a prompt "pivot_trait_XX only works for the trait data table. Try austraits$traits in the data argument"

**Comment by wcornwell** [comment]
this was my comment:

<img width="375" alt="Screen Shot 2021-08-20 at 2 46 10 pm" src="https://user-images.githubusercontent.com/5534161/130180502-00d8bc72-5626-4af1-91e9-3229bd065b1a.png">

could refer to the website with the trait names
