### ISSUE TITLE
maybe australia_raster should be an internal function

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/austraits#24]
since it doesn't seem to be designed to be used by users

**Comment by dfalster** [comment]
Agree!

**Comment by fontikar** [comment]
@dindiarto keen to get your help with this as I am not so familiar with spatial plotting.

I've made the raster internal using:

``` r 
australia_map_raster <- raster::raster("ignore/australia.tif") 
usethis::use_data(australia_map_raster, overwrite = TRUE, internal = TRUE)
```

Internal package data can be accessed like so:
``` r
austraits:::australia_map_raster|
```

But when it comes to plotting with `geom_raster`:
``` r
ggplot() +
    geom_raster(data = austraits:::australia_map_raster, aes(x = .data$x, y = .data$y, fill = .data$ID), show.legend = F) 
#> Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S4 object with class RasterLayer.
```
The object `austraits:::australia_map_raster` doesn't have $x, $y or $ID for the geom to access 

All of these changes are in a seperate branch called `plot` checkout: b91b18e

**Comment by dindiarto** [comment]
@fontikar in my understanding `ggplot( ) + geom_raster ( )` is unable to take raster as an input. Please try the code below taken from t[he austraits paper](https://github.com/traitecoevo/austraits_ms/blob/master/scripts/fig_site_locations.R)

```
## Austraits: site locations plot

#### 01 Get climate data for Australia ####
# Download bioclim data using library (raster)

# one strategy for retrieving data available on web
filename <- "data/australia.tif"

# Read bioclim data using raster package
au_map <- raster::raster(filename) %>%
  # aggregate(fact=6) %>%
  raster::as.data.frame(xy = T)


#### 02 Plot AU basemap ####
ggplot() +
  geom_raster(data = au_map, aes(
    x = x,
    y = y,
    fill = factor(australia)
  )) +
  myTheme -> au_basemap
```

**Comment by fontikar** [comment]
I've made `australia_raster` internal now and its called within the `plot_site_locations` function, but I don't think this is the best practice because it is triggering a warning in `check()`

```checking dependencies in R code ... NOTE
  There are ::: calls to the package's namespace in its code. A package
    almost never needs to use ::: for its own objects:
    ‘austraits’ ‘australia_map_raster’```

**Comment by wcornwell** [comment]
I think you can just remove the `austraits:::` and it should still work?
