### ISSUE TITLE
for the geo plotting add coord_fixed()

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/austraits#25]
this https://ggplot2.tidyverse.org/reference/coord_fixed.html
will make the maps look better :)

**Comment by jrfep** [comment]
Hi @wcornwell , I was looking at the data / code, and actually, it would be very easy to make a [sf object](https://r-spatial.github.io/sf/) out of the sites data:  

```
require(sf)
sites <- austraits$sites %>%  filter(site_property %in% c("longitude (deg)", "latitude (deg)")) %>% mutate(value=as.numeric(value)) %>% filter(!is.na(value)) %>% pivot_wider(names_from = site_property, values_from = value)

sites.ll <- st_as_sf(sites,
                 coords = c("longitude (deg)", "latitude (deg)"),
                 crs = 4326) # assuming the same projection in all coords

plot(sites.ll)
```

**Comment by wcornwell** [comment]
great idea!  `sf` is very elegant.  it has been changing a lot but maybe it's now stable enough to use?
