### ISSUE TITLE
Accessing/exporting data for use in Python (pandas)

### ISSUE THREAD

**Issue by edanweis** [traitecoevo/austraits#27]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Documented example of how to access austraits data in Python for those unfamiliar with R. Short tutorial, or article demonstrating how to export dataframes from R into pandas. 

**Describe alternatives you've considered**
Knowing nothing about R, installing austraits in [RStudio Cloud](https://rstudio.cloud/) but getting error building vignettes. Unclear whether `.rda` can be exported as dataframes, using Feather, or accesing data via some other API (Zenodo?), but with the R convenience functions.

**Additional context**
R may be more commonly used in the scientific community and admittedly there may not be much demand for trait data coming from data scientists (who mainly use Python) - but making it available and visible to other communities, eg: Kaggle, might inspire/encouage collaboration.

**Comment by jrfep** [comment]
Hi @edanweis 
Agree, it would be nice to have a Python tutorial/example, but there is no need to use the R data. 
In the original data record at [Zenodo](https://zenodo.org/record/5112001), there is a zip file containing the csv files with the data. 
I guess it should be relatively easy to replicate most of the examples in the R package from those files using panda.
