### ISSUE TITLE
Table for conversion between AusTraits traits and TRY TraitIDs/TraitNames

### ISSUE THREAD

**Issue by Rekyt** [traitecoevo/austraits#30]
Hi {austraits} maintainers, 👋 

First of all, congratulations for the fantastic organization, package, processes that make out the AusTraits database. You are clearly setting a new standard to set up and manage trait databases. The openness and transparency of all of your work makes it very easy to adapt in different contexts, so thank you a lot for that. I hope to see more databases and tools like the ones your developing.

For one project I have, I am trying to gather as much trait data as possible from global plant trait databases (TRY and BIEN). As Australian species are less covered in global databases I am also using AusTraits to see what's out there.

In one part of my analysis I would like to consolidate the trait table by combining the traits from all three databases. However the conversion of trait names/ids between database is not easy. Especially I was wondering if you had a table to convert the trait name from AusTraits to TRY TraitIDs?
I think it would be great to help the interoperability between plant trait databases.
I've understood you may end up uploading AusTraits to TRY, so at some point this work would need to be done, right?

I have already asked the question the BIEN folks (https://github.com/bmaitner/RBIEN/issues/27#issuecomment-950952853), and they don't have provide such a table either. However, they would really be interested in having one.

Of course a proper table would probably need strict trait definitions that link back to ontologies like https://top-thesaurus.org/ but this would take a massive collective effort of trying to define clearly all the traits. I would rather think of a "simple" table that provides cross-correspondence between trait names or trait IDs.

P.S.: I've posted this feature request here but it may be probably more appropriate in https://github.com/traitecoevo/austraits.build I can move the issue there if you prefer

**Comment by ehwenk** [comment]
I'm glad you'll be using AusTraits for your research!

We have been working on exactly what you're requesting, with the eventual goal of linking our names in our trait definitions "dictionary" with those in TRY wherever possible. The file isn't quite tidy enough to post at this point, but I'll email you a copy directly.

(And the issue probably does fit better in austraits.build, where we have our wishlists list of improvements.)

**Comment by dfalster** [comment]
Hi @Rekyt  - thanks very much for your interest, suggestions and the positive feedback regarding AusTraits. I understand @ehwenk has been corresponding with you via email to address your concerns on a conversion table.

I also wanted to mention that our lab enjoyed your recent preprint (https://ecoevorxiv.org/e3qnz/). In AusTraits we have yet another pipeline beyond those you mentioned, based on the Australian Plant Census (https://biodiversity.org.au), which is the best source for Australian plant taxa but not yet available in the various tools you mentioned in the article.

**Comment by Rekyt** [comment]
Thank you both for your quick answer to the issue. And I'm very glad you already anticipated the correspondence between AusTraits and TRY.

> I also wanted to mention that our lab enjoyed your recent preprint (https://ecoevorxiv.org/e3qnz/). In AusTraits we have yet another pipeline beyond those you mentioned, based on the Australian Plant Census (https://biodiversity.org.au), which is the best source for Australian plant taxa but not yet available in the various tools you mentioned in the article.

Thank you for your feedback. We are currently thinking of working on a follow-up project on taxonomic harmonization pipelines in practice, because we didn't have as much space for that in the current manuscript. So we'll be interested to know more about your workflow and decision process.

**Comment by fontikar** [comment]
Closing, this is being discussed at the [APD repo](https://github.com/traitecoevo/APD)
