### ISSUE TITLE
Pkgdown header is prints incorrect version number

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#32]
**Describe the bug**
When I navigate to https://traitecoevo.github.io/austraits/ the header on the top left corner displays the version number of the develop branch (see screenshot)

**To Reproduce**
1. Go to https://traitecoevo.github.io/austraits/

**Expected behavior**
Based on the DESCRIPTION file, the Version should be 1.0.0.0000 

Wondering if its the trailing zeros??? 

**Screenshots**
![Screen Shot 2022-03-08 at 1 08 51 pm](https://user-images.githubusercontent.com/12161802/157152380-aa3c09ae-38b6-47ad-8081-ee7c8ca6aa08.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac IOS
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by fontikar** [comment]
I am tried this little trick (https://pkgdown.r-lib.org/reference/build_site.html) 
```development:  
 mode: release
 ```
 But still no success. It worked locally and with preview_site(). Will lodge a little issue with pkgdown folks. @dfalster if you have any ideas feel free to chime in :D

**Comment by dfalster** [comment]
Works locally for me too. 

I found the issue. In the settings for the site, the pages were set to be built off develop branch. I just changed to master:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/3589590/159823854-469d6c58-8097-4860-93ee-3cd7e3b68d30.png">

**Comment by dfalster** [comment]
Works correctly now

![image](https://user-images.githubusercontent.com/3589590/159824008-0f2eba26-01d2-4095-b68b-0c27f454967f.jpeg)

**Comment by fontikar** [comment]
Great spot nothing to do with R! Thanks Daniel!
