### ISSUE TITLE
missing(path) is returning TRUE when path has default value

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#33]
**Describe the bug**
This pertains to `load_austraits()`

**To Reproduce**
1. Currently, path has a default value "data/austraits"
2. `load_austraits(version = "3.0.2")` trips the error: `Error in load_austraits(version = "3.0.2") : File path must be supplied!`

**Expected behavior**
Entering debug mode with breakpoint path is set to the default character string, but manually running `missing(path)` returns TRUE when I am expecting FALSE. Function is breaking too early

![Screen Shot 2022-03-08 at 1 54 12 pm](https://user-images.githubusercontent.com/12161802/157157133-6e84ac8b-0ec1-4832-b0cf-d9cd611592bd.png)

Brought to my attention by @wcornwell! Thanks Will!!!!

**Comment by fontikar** [comment]
I'd like to set the same default path for `get_versions()` too, but the same issue arises there, missing returns TRUE even with path has a default string

**Comment by wcornwell** [comment]
i think `missing` is designed this way, though i'm not sure why.  

try:
```{r}
f2 <- function(a='A',b) {
  print( ifelse( missing(a), 'a not specified', paste('a =',a) ) )
  print( ifelse( missing(b), 'b not specified', paste('b =',b) ) )
}

f2(b="test")
```

**Comment by wcornwell** [comment]
https://www.r-bloggers.com/2015/08/function-argument-lists-and-missing/

**Comment by wcornwell** [comment]
```
In general, function authors should avoid the missing() construct and should always specify a default value of NULL for optional arguments. This allows for more systematic sanity checking and passing of arguments to other functions.
```

**Comment by fontikar** [comment]
Thanks for the suggestions @wcornwell! Definitely an improvement to the function

I've decided to set the latest version as the default! and doi = NULL because that is an optional argument. This might be a pain in the future as users will need to set version = NULL first to specify a doi. Ideas how to make this better would be appreciated! 

The problem was that I was using `base::missing` that treats default arguments as missing. Now I am using a combination of is.null and `rlang::is_missing`. 

I added a message for the user if they supplied a doi and a version that didn't match up and it would just precede to load the specified version rather than the doi, but this might be trouble down the road because `version` is always defaulting to `"3.0.2"` now...so maybe I need to tweak this to `stop()`. What do you reckon?

`r
`x <- load_austraits("3.0.2", "10.5281/zenodo.4316516", path = "ignore/data/austraits")
Supplied version and doi does not match! We'll load the requested version 3.0.2
Loading data from 'ignore/data/austraits/austraits-3.0.2.rds'
`
