### ISSUE TITLE
Internal data `austraits_lite` no context info

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#38]
**Describe the bug**
I was testing `as_wide_table` with the internal dataset `austraits_lite` and found a bug! 

**To Reproduce**

```r
devtools::load_all()

austraits_all <- load_austraits(version = "3.0.2", path = "ignore/data/austraits")

dataset_id <- c("Falster_2003", "Falster_2005_1", "Falster_2005_2", "Zanne_2009")

austraits_lite <- extract_dataset(austraits_all, dataset_id)

austraits_lite$contexts #empty list
```
For some reason, these studies ("Falster_2003", "Falster_2005_1", "Falster_2005_2", "Zanne_2009") didn't have associated context data. Is this a common occurrence in the database? Maybe @ehwenk might have an idea? 

**Expected behavior**
Without data in austraits$contexts - as_wide_table breaks

```r
dataset_id_2 <- unique(austraits_all$traits$dataset_id) %>% sample(5)

austraits_lite_new <- extract_dataset(austraits_all, dataset_id_2)

austraits_lite_new$contexts
```
I will resample a new subset for austraits_lite for now to test as_wide_table()

**Comment by dfalster** [comment]
Good catch @fontikar 

It's common not to have any context data for a particular study. What is less common is not to have any context data for any of the studies. 

I'd suggest

- I've run as_wide table on the entire austraits and seems to run fine (and not too slowly either)
- as_wide table should be able to run with and without context data present.  
- updating the austraits lite studies to include at least one with context is possibly a good idea, but maybe hold of, as we're going to need to update again in future.

**Comment by fontikar** [comment]
Good to know! Yes I think that was just a unique subset of data!
