### ISSUE TITLE
Installation from GitHub is failing when vignettes are built

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#40]
**Describe the bug**
Brought to me by @tmesaglio
Errors arise when `remotes::install_github("traitecoevo/austraits", build_vignettes = TRUE)` 
Issue with austraits.RMD on master - see screenshot 
Installation is successful when setting `build_vignettes = FALSE` (@yangsophieee) 

**Expected behavior**
package should just install - vignettes and all - with no issues :) 

**Screenshots**
![image](https://user-images.githubusercontent.com/12161802/163735226-2214805b-0c2b-4b09-8548-29b5b8f3edcc.png)

**Comment by fontikar** [comment]
Works fine on my mac! Seems to be a Windows problem! Testing this on develop branch. Turns out our GitHub Actions only run on Macs only - an oversight for sure

**Comment by fontikar** [comment]
This is strange, GH actions sometimes passes: 
https://github.com/traitecoevo/austraits/actions/runs/2181454271 

but sometimes it also fails: 
https://github.com/traitecoevo/austraits/runs/6058817824?check_suite_focus=true

I think accessing austraits via the API is timing out in some instances

**Comment by fontikar** [comment]
Seems like all Github actions that require interacting with zenodoapi to download austraits have a risk of failing due to timing out: 

```r 
Downloading AusTraits to 'ignore/data/austraits'
trying URL 'https://zenodo.org/api/files/9c997956-8254-4fcc-a17b-5fe1fd079022/austraits-3.0.2.rds'
Warning in utils::download.file(url = url, destfile = fn, method = "auto",  :
  URL 'https://zenodo.org/api/files/9c997956-8254-4fcc-a17b-5fe1fd079022/austraits-3.0.2.rds': Timeout of 60 seconds was reached
Quitting from lines 28-36 (dictionary.Rmd) 
``` 

This might be a good solution to try: https://github.com/weecology/NeonTreeEvaluation_package/issues/29
Maxing out the download timeout: 
```r
timeout_option_backup <- getOption("timeout")
options(timeout = max(2000, getOption("timeout")))

# Call download.file() here

options(timeout = timeout_option_backup)``` 

A solution to installation is to remove the build_vignettes = TRUE as a default 
And point users to the pkgdown website for vignette help!

**Comment by fontikar** [comment]
I've managed to remove the dependency of load_austraits() in the Getting Started.RMD and the Structure.RMD but this is tricky for the trait definitions (i.e. dictionary.RMD) 

I am thinking maybe trying this: https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by dfalster** [comment]
That's possible!

**Comment by fontikar** [comment]
Now the issue is the tests for load_austraits are timing out (wasn't an issue before but best to deal with this). Closing this and creating a new issue
