### ISSUE TITLE
tests for load_austraits are timing out

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#41]
Now the issue is the tests for load_austraits are timing out (wasn't an issue before but best to deal with this). Closing this and creating a new issue

Need to have a closer read of http testing (https://books.ropensci.org/http-testing/introduction.html) 

_Originally posted by @fontikar in https://github.com/traitecoevo/austraits/issues/40#issuecomment-1103382207_

**Comment by jrfep** [comment]
I ran this and got a `timeout` error message:

```
> austraits <- load_austraits(version = "3.0.2", path = "ignore/data/austraits", update = TRUE)
Downloading AusTraits to 'ignore/data/austraits'
trying URL 'https://zenodo.org/api/files/9c997956-8254-4fcc-a17b-5fe1fd079022/austraits-3.0.2.rds'
Content type 'application/octet-stream' length 12325324 bytes (11.8 MB)
=====================================
downloaded 8.8 MB

Error in utils::download.file(url = url, destfile = fn, method = "auto",  : 
  download from 'https://zenodo.org/api/files/9c997956-8254-4fcc-a17b-5fe1fd079022/austraits-3.0.2.rds' failed
In addition: Warning messages:
1: In utils::download.file(url = url, destfile = fn, method = "auto",  :
  downloaded length 9206770 != reported length 12325324
2: In utils::download.file(url = url, destfile = fn, method = "auto",  :
  URL 'https://zenodo.org/api/files/9c997956-8254-4fcc-a17b-5fe1fd079022/austraits-3.0.2.rds': Timeout of 60 seconds was reached
```
From the help page of utils::download.file: 

> The timeout for many parts of the transfer can be set by the option timeout which defaults to 60 seconds. This is often insufficient for downloads of large files (50MB or more) and so should be increased when download.file is used in packages to do so. Note that the user can set the default timeout by the environment variable R_DEFAULT_INTERNET_TIMEOUT in recent versions of R, so to ensure that this is not decreased packages should use something like
```
options(timeout = max(300, getOption("timeout")))  
```

So, I tried this:
```
options(timeout = max(300, getOption("timeout"))) 
austraits <- load_austraits(version = "3.0.2", path = "ignore/data/austraits", update = TRUE)
```
and it worked!

I guess this will depend on the user's internet connection, so it is probably best to suggest the user to change this option if needed.

**Comment by fontikar** [comment]
Thanks a good suggestion @jrfep!

 I suppose I can set `options(timeout = max(300, getOption("timeout")))`  in my tests for this function

But great idea to put it in the vignettes for users!

**Comment by dfalster** [comment]
Would be better to modify timeout within the load Austraits function, then restore previous values.
