### ISSUE TITLE
Dictionary in vignette has a problem reading empty description in yaml file

### ISSUE THREAD

**Issue by jrfep** [traitecoevo/austraits#43]
**Describe the bug**
Dictionary in vignette has a problem reading empty description in yaml file

**Example**
1. Go to https://traitecoevo.github.io/austraits/articles/dictionary.html#dispersal_syndrome 
2. Scroll down to 'mud_on_car'
3. See error:
> mud_on_cars: Dispersules with elaiosomes (specialised nutritious appendages) that make them attractive for capture, transport and use by ants or related insects; true dispersal syndrome
> myrmecochory: water; e.g. floating/submerged in fresh/saltwater currents
> nautohydrochory: water; diaspore is propelled by action of rain on plant structure/wetting by rain or dew
> ombrohydrochory: methods originating from parent plant or diaspore
> etc.

**Expected behavior**

I suspect the `mud_on_cars` entry has an empty description in the original YAML file, causing the problem. This can be fixed by updating the YAML file from austraits, but the R code should detect this and output something like:

> mud_on_cars: ...[Missing description]...
> myrmecochory: Dispersules with elaiosomes (specialised nutritious appendages) that make them attractive for capture, transport and use by ants or related insects; true dispersal syndrome
> nautohydrochory: water; e.g. floating/submerged in fresh/saltwater currents
> ombrohydrochory: water; diaspore is propelled by action of rain on plant structure/wetting by rain or dew
> etc.

**Additional context**
I think the problem is in line 47 of `vignettes/dictionary.Rmd`:
- `paste0("    - *",elements$values %>% names(), "*: ", elements$values %>% unlist(), collapse="\n"))),`

Using `unlist()` will silently ignore the missing value in `elements$value` and you get two vectors of different length.

**Comment by jrfep** [comment]
```
austraits <- load_austraits(version = "3.0.2", path = "ignore/data/austraits", update = FALSE)
definitions <- austraits$definitions
trait='dispersal_syndrome'
elements <- austraits$definitions$traits$elements[[trait]]
> length(elements$values)
[1] 40
> length(names(elements$values))
[1] 40
> length(unlist(elements$values))
[1] 39
```

It should work without a call to `unlist()`
- `paste0(" - *",elements$values %>% names(), "*: ", elements$values, collapse="\n")`

Or consider using `sprintf`
- `sprintf(" - *%s*: %s", names(elements$values),elements$values)`

**Comment by fontikar** [comment]
Goodness me! Thank you so much for finding this @jrfep! Takes some keen eyes to spot this one! I've just implemented `paste0(" - *",elements$values %>% names(), "*: ", elements$values, collapse="\n")` and reknitted the vignettes! @ehwenk just tagging you in this issue to let you know! Not sure if [austraits.build](https://github.com/traitecoevo/austraits.build) will have the same issue for `mud_on_car`
