### ISSUE TITLE
Update to work with revised austraits format

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits#50]
The data in the next release of austraits will have slightly altered format. We'll need some minor tweaks to keep functions working with both new and old format.

**Comment by fontikar** [comment]
Oh sounds great! Perhaps I can get my hands on a subset of the next AusTraits version release so I can get things testing and adjusted!

**Comment by dfalster** [comment]
Great, I'll pass it on when ready. Will be in early August

**Comment by fontikar** [comment]
Major updates have been done to the core functions of `austraits` to work with both formats of the database. 
See [release notes](https://github.com/traitecoevo/austraits/releases/tag/v2.1.1) of what has been changed in the latest package release:
