### ISSUE TITLE
`join_` family updates, underscores and variable name changes

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#55]
Major changes include (copied from @ehwenk notes)
- the field `traits$collection_date` now replaces all three of `traits$date`, `methods$year_collected_start`, `methods$year_collected_end`; it is either a fixed value formatted as yyyy-mm-dd/yyyy-mm-dd (or yyyy-mm or yyyy, depending what we have) or read in from a column

- "taxonRank" -> `taxon_rank`
- "acceptedNameUsageID" -> `accepted_name_usage_id`

etc... see the schema, but we've now renamed everything to fit the AusTraits `underscore` convention

**Comment by fontikar** [comment]
Need to think carefully about the vars that get joined with each `join_` function. Currently it varies between versions. Maybe remove the option for user to choose from the list, so that its hard coded in the function? 

e.g. 

```
join_methods <- function(austraits, vars =  c("methods", "year_collected_start", "year_collected_end", "collection_type")) {
  # Switch for different versions
  version <- austraits$build_info$version %>% as.character()
  
  switch (version,
          '3.0.2.9000' = join_methods2(austraits, vars =  c("methods")),
          '3.0.2' = join_methods1(austraits, vars =  c("methods", "year_collected_start", "year_collected_end", "collection_type"))
  )
  
}
```

**Comment by fontikar** [comment]
@dfalster and I had a chat about how to update `join_contexts` for the new version of AusTraits. He has written a function that seems to work ok for two use cases. 

@dfalster  would you be able to share the function here please? 
@ehwenk we thought you would be the perfect person to test the function out with interesting studies that have lots of `link_ids` or `context_property(s)`.

**Comment by dfalster** [comment]
Here's my draft for joining in the context info

@ehwenk - would be great if you could check this works, i.e. that the rejoined table has the right context info for the right rows, compared to the raw dataset?

```
x <- remake::make("Crous_2013")

traits2 <- x$traits

for(v in unique(x$contexts$link_id)){
 
 context_sub <- 
  x$contexts %>%
  dplyr::select(-dplyr::any_of(c("category", "description"))) %>%
  dplyr::filter(link_id == v) %>% 
  tidyr::pivot_wider(values_from = value, names_from = context_property) %>%
  tidyr::pivot_wider(names_from = link_id, values_from = link_vals)

  traits2 <- 
  left_join(by = c("dataset_id", v),
    traits2,
    context_sub
    )
}


```

**Comment by ehwenk** [comment]
@dfalster The function works well for instances when there is a single context within a category - as is the case for method context and temporal context in this example. However, where there are multiple contexts within a category, there needs to be an extra step to decompress the comma-delimited string of numbers into multiple rows.

**Comment by fontikar** [comment]
@ehwenk thats great feedback! Would you have a dataset_id as an example, perhaps one in the .rds file you've sent me? Perhaps I can have a crack at this today!

**Comment by dfalster** [comment]
ah yes. 

@ehwenk - please suggest an example

@fonti - you would use the function `seperate_rows`

**Comment by ehwenk** [comment]
@fontikar @dfalster 

Crous_2013 is a great one to use, since it has both "1 property categories" (temporal, method contexts) and "multi-property categories (treatment)

**Comment by fontikar** [comment]
Ah I thought we tested that one but we didn't check thoroughly! Will report back!

**Comment by fontikar** [comment]
Leaving a note here for myself: 

- [ ] After joining, we need to reassign output as class("austraits") so the print function works
- [ ] Do we make the version specific functions internal? `join_taxonomy` for example

These may become their own seperate issues later on if needed

**Comment by fontikar** [comment]
I think upgrades to `join_` family are complete and to my liking! 

```
pacman::p_load(purrr)

austraits <- readRDS("ignore/data/austraits/austraits_2022_11_03.rds") # new version
attr(austraits, "class") <- "austraits"

austraits_32 <- load_austraits(version = "3.0.2", path = "ignore/data/austraits")
austraits %>% join_all() %>% pluck("traits")
austraits_32 %>% join_all() %>% pluck("traits")

austraits %>% join_locations() %>% pluck("traits")
austraits_32 %>% join_sites() %>% pluck("traits")
austraits_32 %>% join_locations() %>% pluck("traits")

austraits %>% join_taxonomy() %>% pluck("traits")
austraits_32 %>% join_taxonomy() %>% pluck("traits")

austraits %>% join_contexts() %>% pluck("traits")
austraits_32 %>% join_contexts() %>% pluck("traits")

austraits %>% join_methods() %>% pluck("traits")
austraits_32 %>% join_methods() %>% pluck("traits")
```

**Comment by dfalster** [comment]
Super @fontikar !!!

**Comment by fontikar** [comment]
Brought to attention by @yangsophieee 

Notes to self.

Need to improve the documentation around the `...` that is passed to vars in each `join_` function. 
For <=v3.0.2, the function needs all cols "dataset_id" "context_name", "context_property", "value" to join successfully. passing only one of 4 would break the function. This seems way too unstable and seems to encourage a 'hard coded' approach where we tell users that all context info will be joined, and they can further remove if they need afterwards. 

I need to come back to this with fresh eyes because I think vars will being passed to filter specific context_property and not to select the cols per se.

**Comment by fontikar** [comment]
Joining taxonomy and joining methods are currently adding more rows despite using `distinct` in the functions. Need to look over those joins more closely

```austraits_4.0.0 %>% join_all() %>% pluck('traits') %>% nrow()
[1] 1264510
> austraits_4.0.0$traits %>% nrow()
[1] 1257443
> austraits_4.0.0 %>% join_taxonomy() %>% pluck('traits') %>% nrow()
[1] 1257658
> austraits_4.0.0 %>% join_locations() %>% pluck('traits') %>% nrow()
[1] 1257443
> austraits_4.0.0 %>% join_methods() %>% pluck('traits') %>% nrow()
[1] 1264295
> 1264295-1257443
[1] 6852
> 1257658-1257443
[1] 215
> 6852+215
[1] 7067
> 6852+215 + austraits_4.0.0$traits %>% nrow()
[1] 1264510
```
