### ISSUE TITLE
Renamed functions  e.g. (plot_locations, join_locations) may need a soft deprecation process

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#59]
We discussed options to keep old functions working and thought the roxygen tag `#' @alias` would do the trick, but after some careful digging, it looks like this only allows functions tagged with `@alias` to pull up a more current help file e.g  `?join_sites` would pull up the more recent `join_locations` .Rd file. 

I think its sensible and kind to keep the "old" functions e.g `plot_site_locations` and `join_sites` working. 
I like the idea of [this wrapper approach: ](https://stackoverflow.com/questions/10099128/are-there-best-recommended-practices-to-follow-when-renaming-functions-in-a-new)

Would look something like this: 

```
plot_site_locations <- function(XXX){
 .Deprecated("plot_locations", package = "austraits")
 [old function content]
}

plot_locations <- function(XXX){
[new function content]
}
``` 
Probably good to use [lifecycle badges too ](https://lifecycle.r-lib.org/articles/stages.html#deprecated)

Thoughts? Happy to discuss in person!

**Comment by dfalster** [comment]
I like the idea with the wrapper. Set it up to run, but only with the old version of the data. 

A slight variant - write a new function that takes either the old of new data

```
plot_locations <- function(XXX){
[new function content]
# maybe include switch statement to make the old data work with new function

}
```

then 

```
plot_site_locations <- function(XXX){
 .Deprecated("plot_locations", package = "austraits")
 plot_locations(XXX)
}
```

**Comment by fontikar** [comment]
Haha! We have a similar line of thinking @dfalster I thought that would be a good idea too!

Unfortunately, its tricky to use the switch statement and call it within the old `plot_site_locations`
This is because:
1) `plot_site_locations` takes the `traits` table as an input
e.g
```
austraits_old <- load_austraits(version = "3.0.2", path = "ignore/data/austraits")
austraits_old %>% extract_dataset("Falster_2003") -> Falster_2003

Falster_2003 %>% join_all() %>% purrr::pluck("traits") %>%  plot_site_locations(feature = "trait_name")
```

2) Current approach with switch statements is to accept the entire `austraits` list as an input and switch based on version in `austraits$build_info$version`

```
austraits_new %>% extract_dataset("Crous_2013") -> Crous_2013
Crous_2013 %>% join_all() %>% plot_locations(feature = "basis_of_record")

Falster_2003 %>% join_all() %>% plot_locations(feature = "collection_type")
```

What I've done at the moment is to keep `plot_site_locations` alive but with deprecation statement but it doesn't pass its contents on to `plot_locations `because of point 2) 

I think it is possible to implement what you are suggesting but may need a fresh pair of eyes and drawing things out together.

Also I think its  worth discussing whether our functions should be `traits` table focussed or object focussed. I am drawn to latter and keep it consistent across all functions.

**Comment by fontikar** [comment]
Notes for Fonti to return to: 

Have option to accept list or traits table? 
- if list and versions <= 3.0.2, isolate list and pass to plot_locations1
 
 If we want to keep traits table as an input like the original function.
- We can try switch on something else? ncol(traits) can tell us if its version <= 3.0.2 or not?
