### ISSUE TITLE
A new approach to handle different versions of vignettes

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#63]
Since there will be multiple versions of AusTraits, I think it would be sensible to retain two versions of the structures and trait definitions vignette. I think h organising them with a submenu would be sensible! 

For certain functions that create different outputs e.g `trait_pivot_wider` but have the same syntax, it might be sensible to use [tabsets](https://pkgdown.r-lib.org/articles/test/rendering.html?q=tabset#tabsets) to delineate these. Or maybe the tutorial entirely is tabsetted by <=3.0.2  and >3.0.2?! 

Just brainstorming ideas!

**Comment by dfalster** [comment]
Seems sensible!

**Comment by fontikar** [comment]
For some reason I am unable to do make tabsets! I suspect because these are incompatible with .RMD vignettes that have these in the yaml header:
```
vignette: >
  %\VignetteIndexEntry{austraits}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
  ```
RMD with these headers are for building vignettes that can be viewed with`vignettes()` and `browseVignettes()`

Tabsets are possible but perhaps with RMD that doesn't have the fancy yaml headers
e.g https://github.com/r-lib/pkgdown/blob/main/vignettes/test/rendering.Rmd#L144

We have two options:
1) No fancy vignette but have tabsets for pkgdown.
2) The fancy vignette with is going to be written for AusTraits 4.0.0 or newer
and we have a seperate regular RMD for AusTraits 3.0.2 that can be found via pkgdown website

I am leaning more for 2.

**Comment by fontikar** [comment]
![Screen Shot 2023-01-13 at 5 12 30 pm](https://user-images.githubusercontent.com/12161802/212250170-02881b71-abe8-4317-be54-612760df8523.png)

I have aborted the 'tabset' approach as this doesn't work well with Vignette framework that allows users to call `vignette("austraits")`. Instead I have opted to make the main tutorial on the pkgdown website to present the functions and output that work with AusTraits 4.0.0 and created a seperate tutorial to present the same workflow for AusTraits 3.0.2 and older (as shown in screenshot!) 

All of this work is on the `vignette` branch and has not been merged to develop as I wanted to get @dfalster's feedback
I suggest pulling this branch and build the site and preview:

```
library(pkgdown)
build_site()
```

We can revisit this and merge when you feel it is appropriate!

**Comment by fontikar** [comment]
Closing this as this won't be an issue with #96
