### ISSUE TITLE
Organise Trait definitions page starting letter A-Z

### ISSUE THREAD

**Issue by daxkellie** [traitecoevo/austraits#70]
Hi {austraits} team! Big fan 😃 

I have been trying to go through the incredible number of traits by using the handy [Trait definitions page on the package website](https://traitecoevo.github.io/austraits/articles/dictionary.html#cell_internal_parenchyma_p_per_fresh_mass). At the moment, there are so many traits that when using the website, the menu in the right hand pane doesn't work correctly (it doesn't scroll until you reach the very bottom).

Would it be possible to sort this list by setting the top headers as the letters A-Z, rather than the trait names? I think this will make it easier to search traits and hopefully fix the right-pane menu. For example:
```r
# A
### accessory_cost_mass
### accessory_cost_fraction

# B
### bark_mass_area
### bark_density

# etc...
```

**Comment by dfalster** [comment]
Hi @daxkellie ! Thanks for the positive work and feedback. 

The documentation of trait definitions is actually moving to it's own repository, <https://traitecoevo.github.io/APD/>

We now have the dictionary accessible as

- human readable text at <https://traitecoevo.github.io/APD/> and via <https://w3id.org/APD/>
- on zenodo at <https://zenodo.org/record/8040790>
- on ARDCs Research Vocals at <https://vocabs.ardc.edu.au/viewById/649>

We will but haven't yet updated the documentation in this repo to point to these locations

Interested to hear how usable you find these other sources!

**Comment by dfalster** [comment]
Oh yeah, and a paper available at https://www.biorxiv.org/content/10.1101/2023.06.16.545047.abstract

**Comment by fontikar** [comment]
I will close this issue in favour of #74 which has a much clearer scope! I do like Dax's suggestion about the alphabetical ordering which the APD has already.
