### ISSUE TITLE
as_wide_table function with austraits v 4.2.0

### ISSUE THREAD

**Issue by dcol2804** [traitecoevo/austraits#73]
**Describe the bug**
The as_wide_table function is breaking with the new version 4.2.0. 

**To Reproduce**
1. Run these lines of code: 
remotes::install_github("traitecoevo/austraits")
library(austraits) 
austraits <- load_austraits(path="data/austraits", version = "4.2.0")

**Expected behavior**
I expected a wide table as I get if I run the function on the previous version:
austraits <- load_austraits(path="data/austraits", version = "4.1.0")

**Screenshots**
The error message thrown is the following (perhaps a problem with pivoting wider without unique ids?):
![image](https://github.com/traitecoevo/austraits/assets/50344360/08324a16-d9d2-4742-bfcc-11282133f493)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 

**Additional context**

**Comment by fontikar** [comment]
Hey @dcol2804 thanks for pointing this out! That is a bummer that 4.2.0 can't pivot wider - tis the curse of relational databases!

From my initial dig around the code, I've isolated the problem with contexts and I suspect it doe have something to do with non-uniqueness with link_vals as your error message suggests! 

@ehwenk any ideas what kinda trait is `time to flowering type` is? Its interesting that its not snake case? 

```
library(austraits)
my_path <- c("~/Dropbox/0 - Job/austraits/ignore/data/")
at_420 <- load_austraits(version = "4.2.0", path = my_path)
at_410 <- load_austraits(version = "4.1.0", path = my_path)
at_302 <- load_austraits(version = "3.0.2", path = my_path)

# as_wide_table
wide_at_302 <- as_wide_table(at_302)
wide_at_410 <- as_wide_table(at_410)
wide_at_420 <- as_wide_table(at_420)

# Exploring bug
jcontext_at_420 <- at_420 |> join_contexts(collapse_context = TRUE) # Breaks here
at_420 |> join_contexts() # Also occurrs here, so not about collapsing context, its upstream from there.

# Suspect bug is in here L182-194

context_ids <- 
  unique(contexts2[[id]]$link_id)

for(v in context_ids[!is.na(context_ids)]) {
  
  context_sub <- 
    contexts2[[id]] %>%
    dplyr::select(-dplyr::any_of(c("category", "description"))) %>%
    dplyr::filter(link_id == v) %>% 
    tidyr::separate_rows(link_vals) %>% 
    tidyr::pivot_wider(values_from = value, names_from = context_property) %>%
    tidyr::pivot_wider(names_from = link_id, values_from = link_vals)

```

**Comment by fontikar** [comment]
Oooh its a context_property! 
```
at_420$contexts$context_property |> stringr::str_subset("flowering")  |> unique()
```

**Comment by fontikar** [comment]
Some more digging: 

Culprits are `Kubiak_2009", "vanderMoezel_1987"`, the combination of `dataset_id, `time to flowering type`, link_id` resulted in dups in `link_vals`

``` r
library(austraits)
#> Loading required package: RefManageR
#> Thanks for showing interest in `austraits`! Please consider citing this package - citation('austraits')
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(stringr)
library(tidyr)

my_path <- c("~/Dropbox/0 - Job/austraits/ignore/data/")
at_420 <- load_austraits(version = "4.2.0", path = my_path)
#> Loading data from '~/Dropbox/0 - Job/austraits/ignore/data//austraits-4.2.0.rds'
at_410 <- load_austraits(version = "4.1.0", path = my_path)
#> Loading data from '~/Dropbox/0 - Job/austraits/ignore/data//austraits-4.1.0.rds'
at_302 <- load_austraits(version = "3.0.2", path = my_path)
#> Loading data from '~/Dropbox/0 - Job/austraits/ignore/data//austraits-3.0.2.rds'

# as_wide_table
wide_at_302 <- as_wide_table(at_302)
wide_at_410 <- as_wide_table(at_410)
wide_at_420 <- as_wide_table(at_420)
#> Warning: Values from `link_vals` are not uniquely identified; output will contain
#> list-cols.
#> • Use `values_fn = list` to suppress this warning.
#> • Use `values_fn = {summary_fun}` to summarise duplicates.
#> • Use the following dplyr code to identify duplicates.
#>   {data} %>%
#>   dplyr::group_by(dataset_id, `time to flowering type`, link_id) %>%
#>   dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
#>   dplyr::filter(n > 1L)
#> Error in `dplyr::left_join()` at austraits/R/join_all.R:197:8:
#> ! Can't join `x$entity_context_id` with `y$entity_context_id` due to
#>   incompatible types.
#> ℹ `x$entity_context_id` is a <character>.
#> ℹ `y$entity_context_id` is a <list>.

# Explore contexts
at_420$contexts$context_property |> stringr::str_subset("flowering")  |> unique()
#> [1] "time to flowering type" "flowering extent"

contexts_at_420 <- at_420$contexts

# Filter out the contexts
str_which(contexts_at_420$context_property, "flowering type")
#>  [1]   67   68  202  203  569  570  571  677 1171 1172 1173 1174 1337 1338

# Can't seem to get filter() to work
time_to_flowering_type_context <- contexts_at_420 |> 
  dplyr::slice(str_which(contexts_at_420$context_property, "flowering type"))

# What are the unique link_ids for each of these studies
time_to_flowering_type_context |> 
  group_by(dataset_id) |> 
  summarise(context_ids = unique(link_id))
#> # A tibble: 6 × 2
#>   dataset_id        context_ids      
#>   <chr>             <chr>            
#> 1 Burrows_2008      entity_context_id
#> 2 Clarke_2009       entity_context_id
#> 3 Kubiak_2009       entity_context_id
#> 4 NSWFRD_2014       entity_context_id
#> 5 Yang_2023         entity_context_id
#> 6 vanderMoezel_1987 entity_context_id

# Seperate link_vals and first pivot wider
first_pivot <- time_to_flowering_type_context |> 
  select(-c(category, description)) |> 
  group_by(dataset_id) |> 
  tidyr::separate_rows(link_vals) |> 
  tidyr::pivot_wider(values_from = value, names_from = context_property) 
  
first_pivot
#> # A tibble: 19 × 4
#> # Groups:   dataset_id [6]
#>    dataset_id        link_id           link_vals `time to flowering type`
#>    <chr>             <chr>             <chr>     <chr>                   
#>  1 Burrows_2008      entity_context_id 02        from resprouting        
#>  2 Burrows_2008      entity_context_id 01        from seed               
#>  3 Clarke_2009       entity_context_id 02        from resprouting        
#>  4 Clarke_2009       entity_context_id 01        from seed               
#>  5 Kubiak_2009       entity_context_id 03        from resprouting        
#>  6 Kubiak_2009       entity_context_id 02        from resprouting        
#>  7 Kubiak_2009       entity_context_id 01        from resprouting        
#>  8 Kubiak_2009       entity_context_id 05        from seed               
#>  9 Kubiak_2009       entity_context_id 06        from seed               
#> 10 Kubiak_2009       entity_context_id 04        from seed               
#> 11 Kubiak_2009       entity_context_id 10        unknown                 
#> 12 Kubiak_2009       entity_context_id 09        unknown                 
#> 13 NSWFRD_2014       entity_context_id 01        from resprouting        
#> 14 vanderMoezel_1987 entity_context_id 01        from seed               
#> 15 vanderMoezel_1987 entity_context_id 03        from resprouting        
#> 16 vanderMoezel_1987 entity_context_id 04        unknown                 
#> 17 vanderMoezel_1987 entity_context_id 02        unknown                 
#> 18 Yang_2023         entity_context_id 02        from resprouting        
#> 19 Yang_2023         entity_context_id 01        from seed

# Identify dups
first_pivot %>%
  dplyr::group_by(dataset_id, `time to flowering type`, link_id) %>%
  dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
  dplyr::filter(n > 1L) 
#> # A tibble: 4 × 4
#>   dataset_id        `time to flowering type` link_id               n
#>   <chr>             <chr>                    <chr>             <int>
#> 1 Kubiak_2009       from resprouting         entity_context_id     3
#> 2 Kubiak_2009       from seed                entity_context_id     3
#> 3 Kubiak_2009       unknown                  entity_context_id     2
#> 4 vanderMoezel_1987 unknown                  entity_context_id     2

first_pivot |> filter(dataset_id %in% c("Kubiak_2009", "vanderMoezel_1987"))
#> # A tibble: 12 × 4
#> # Groups:   dataset_id [2]
#>    dataset_id        link_id           link_vals `time to flowering type`
#>    <chr>             <chr>             <chr>     <chr>                   
#>  1 Kubiak_2009       entity_context_id 03        from resprouting        
#>  2 Kubiak_2009       entity_context_id 02        from resprouting        
#>  3 Kubiak_2009       entity_context_id 01        from resprouting        
#>  4 Kubiak_2009       entity_context_id 05        from seed               
#>  5 Kubiak_2009       entity_context_id 06        from seed               
#>  6 Kubiak_2009       entity_context_id 04        from seed               
#>  7 Kubiak_2009       entity_context_id 10        unknown                 
#>  8 Kubiak_2009       entity_context_id 09        unknown                 
#>  9 vanderMoezel_1987 entity_context_id 01        from seed               
#> 10 vanderMoezel_1987 entity_context_id 03        from resprouting        
#> 11 vanderMoezel_1987 entity_context_id 04        unknown                 
#> 12 vanderMoezel_1987 entity_context_id 02        unknown
```

<sup>Created on 2023-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dcol2804** [comment]
Thanks @fontikar! Got the as_wide_table function working by removing after finding a few more sources of duplicate rows: 

austraits$traits = austraits$traits %>% filter(!(dataset_id == "eFLOWER_Dun_2022" & taxon_name == "Abrotanella nivigena" ))
austraits$contexts = austraits$contexts %>% filter(!dataset_id %in% c("Kubiak_2009", "vanderMoezel_1987"))
austraits$locations = austraits$locations %>% filter(!(dataset_id == "Ahrens_2019" & location_id %in% c("08", "09")))
austraits$methods = austraits$methods %>% filter(!dataset_id %in% c("Morgan_2021", "Nano_2011", "Purdie_1976")) %>% dplyr::select(-value_type)

aus_wide = as_wide_table(austraits)

@ehwenk, I'll see if I can create some custom R code to give these unique identifiers :)

**Comment by ehwenk** [comment]
Without actually looking in the database right now (can look in 24 hours) a few thoughts:
- 'Time to flowering type' is a context property which is why it isn't camel case.
- part of the non-pivoting might be because we've now changed around names of some identifiers. Temporal_id, method_id, treatment_id and plot_id all now have the word context in them. And there is a new column called method_id that appears in traits and methods.
-  Sophie had written a pivot test - see recent traits.build commits. If you look at her code you'll see the collection of columns we're now using to pivot. I'm guessing it has grown?

**Comment by dcol2804** [comment]
So if these new columns are added into the pivot list then all these issues will probably be resolved!

**Comment by fontikar** [comment]
> Sophie had written a pivot test - see recent traits.build commits. If you look at her code you'll see the collection of columns we're now using to pivot. I'm guessing it has grown?
@yangsophieee can you comment on this and points us to these pls :D  THANKS 🏆

**Comment by yangsophieee** [comment]
Hey! Sorry for the late reply. 

Here on [Line 773 of testdata.R](https://github.com/traitecoevo/traits.build/blob/2345b0a5619892b44e8845171c9f17dab7268b91/R/testdata.R#L773): 

```
c("dataset_id", "trait_name", "value", "observation_id", "source_id", "taxon_name",
              "entity_type", "life_stage", "basis_of_record", "value_type", "population_id", "individual_id",
              "repeat_measurements_id", "temporal_context_id", "method_id", "method_context_id", "entity_context_id",
              "original_name")
```

However, note that `repeat_measurements_id` doesn't exist on the develop branch yet, it's on a branch which will be merged in soon. So I guess you can remove it to get it working for now!

**Comment by fontikar** [comment]
I suspect thats the one we need to make it pivot nicely for 4.2.0

**Comment by ehwenk** [comment]
The grouping variables are:

```
group_by(dataset_id, source_id, taxon_name, original_name, observation_id, method_id, temporal_id, entity_context_id, value_type, basis_of_record) %>% 
```

(With and without `value_type`. I can't remember why we wrote the switch for value_type - I guess to keep rows lumped when possible. )

What is frustrating about having to make this change, is that `basis_of_record` is in this list only because of a different error. It should have been part of the variables to create `observation_id`'s (and is now on traits.build), but there is a single study `Britton_1994` where we didn't catch that there are two sets of measurements for the same trait, from field vs lab. Those are obviously different observations, but have the same `observation_id` in version 4.2.0. I wish we'd caught that! So basis_of_record is added now, then removed again. It won't break anything to add it, so I think that is the best option.

**Comment by fontikar** [comment]
Gotcha lemme try implement this and have a test :) thanks for digging that up!! 🏆

**Comment by dcol2804** [comment]
Also @fontikar, I'm not sure if you'll need this piece of the puzzle or not.. but the methods table in 4.2.0 has a column which shouldn't be there called "value_type". Its mostly blank so best to chuck it out. When I merge the methods table with the traits table (which also has the real "value_type" column, I get  "value_type.y" and "value_type.x". You might need to add a line to get rid of it in any relevant functions until the next release.

**Comment by fontikar** [comment]
@dcol2804 

> Also @fontikar, I'm not sure if you'll need this piece of the puzzle or not.. but the methods table in 4.2.0 has a column which shouldn't be there called "value_type". Its mostly blank so best to chuck it out. When I merge the methods table with the traits table (which also has the real "value_type" column, I get "value_type.y" and "value_type.x". You might need to add a line to get rid of it in any relevant functions until the next release.

That is useful! But I think that this is better placed for  `austraits.build` team @ehwenk @yangsophieee ?

**Comment by fontikar** [comment]
After speaking with @ehwenk, we decided we will not support `as_wide_table` for austraits 4.2.0, as it was a short-lived version with minor bugs that prevented it from pivoting.  We suggest users to work with the latest versions of AusTraits version 5.0.0 or newer can become `as_wide_table` more feasibly
