### ISSUE TITLE
join_contexts failing on `vanderMoezel_1987` in v 4.2.0

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits#76]
the `join_contexts` function is failing at `vanderMoezel_1987` (v4.2.0), because there are two entries for a context that map to the same context property value - and therefore break the function the second place `pivot_wider` is used:

```  
dataset_id        link_id           link_vals `time to flowering type`
  <chr>             <chr>             <chr>     <chr>                   
1 vanderMoezel_1987 entity_context_id 01        from seed               
2 vanderMoezel_1987 entity_context_id 03        from resprouting        
3 vanderMoezel_1987 entity_context_id 04        unknown                 
4 vanderMoezel_1987 entity_context_id 02        unknown  
```

I've fixed this in the current austraits.build repository, but in the meantime, vanderMoezel_1987 needs to be added flagged as a problem study within the `join_contexts` function. (Meanwhile `Hall_1981` is no longer a problem study in v4.2.0.)

@yangsophieee and I decided today to add tests to traits.build that ensure the austraits functions work as each new dataset is added to ensure these problems stop surfacing after releases!

**Comment by ehwenk** [comment]
@yangsophieee just pointed out that recent edits to the traits.build workflow now automatically collapse identical context property values, so this is no longer a problem.

**Comment by fontikar** [comment]
Not supporting 4.2.0 closing after discussion with @ehwenk
