### ISSUE TITLE
load_austraits broken

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#79]
```
 at42 <- load_austraits(version = "4.2.0", path = "ignore/data", update = TRUE)
Error in open.connection(con, "rb") : 
  cannot open the connection to 'https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true'
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open URL 'https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true': HTTP status was '404 Not Found'
>     res <- jsonlite::read_json("https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true",
+                                simplifyVector = T)
Error in open.connection(con, "rb") : 
  cannot open the connection to 'https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true'
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open URL 'https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true': HTTP status was '404 Not Found'
```

Not sure what is going on, zenodo api had an upgrade, but their changelog doesn't seem to say anything that majorly affects us....

**Comment by fontikar** [comment]
https://zenodo.org/api/records/8353840

This works but conceptrecid doesn't...

**Comment by fontikar** [comment]
https://help.zenodo.org/docs/about/whats-changed/#records-commuinties

**Comment by dfalster** [comment]
Gosh, bad timing with Lizzy running a workshop. I've just looked at various docs and can't figure out why our existing method fails.  However I have possible solution (see end below)

# Illustrating issue with existing methods

## For austraits

**Concept id**

conceptrecid: 3568417
doi: https://zenodo.org/doi/10.5281/zenodo.3568417 [works]
url: https://zenodo.org/records/3568417 [works]
api1: https://zenodo.org/api/records/3568417 [fails]
api2 (using search and all versions, i.e. our method): https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true [fails]

**Specifc record**

doi: https://zenodo.org/doi/10.5281/zenodo.8353840 [works]
api1: https://zenodo.org/api/records/8353840 [works]
api2 (using search and all versions, i.e. our method): https://zenodo.org/api/records/?q=id: 8353840&all_versions=true [fails]

But I don't think it's austraits specific. Here's 

## an entirely different repo showing the same behaviour

conceptrecid: 8436716
doi: https://zenodo.org/doi/10.5281/zenodo.8436716 [works]
url: https://zenodo.org/records/8436716 [works]
api1: https://zenodo.org/api/records/8436716 [fails]
api2 (using search and all versions, i.e. our method): https://zenodo.org/api/records/?q=conceptrecid:8436716&all_versions=true [fails]

However, again, calling a record directly works, but not using our method for querying

doi: https://zenodo.org/doi/10.5281/zenodo.8436717 [works]
api1: https://zenodo.org/api/records/8436717 [works]
api2 (using search and all versions, i.e. our method): https://zenodo.org/api/records/?q=id:8436717&all_versions=true

So it seems there's two things going on

1. Our existing method of queuing api is not working, whether we query via concept id or id
2. Concept id not recognised in direct requests for records, e.g. https://zenodo.org/api/records/8436716  (but I'm not sure if it ever did)

# Possible solution

Calling this link seems to return a json with the info with all versions included:

https://zenodo.org/api/records/3568418/versions

Does this work for package?

**Comment by fontikar** [comment]
Revisiting this conversation here @ehwenk  and @dfalster which versions do we want to display using `get_versions`

``` pre_res |> 
+   dplyr::mutate(version = gsub("v", "", version))
   publication_date                    doi version
1        2023-09-18 10.5281/zenodo.8353840   4.2.0
2        2023-01-30 10.5281/zenodo.7583087   4.1.0
3        2022-11-27 10.5281/zenodo.7368074   4.0.0
4        2021-07-14 10.5281/zenodo.5112001   3.0.2
5        2021-07-14 10.5281/zenodo.5099552   3.0.1
6        2021-07-14 10.5281/zenodo.5099545   3.0.0
7        2020-12-11 10.5281/zenodo.4316550   2.1.0
8        2020-07-08 10.5281/zenodo.4316516   2.0.0
9        2019-12-09 10.5281/zenodo.3583418   0.9.1
10       2019-12-09 10.5281/zenodo.3568429   0.9.0
11       2019-12-09 10.5281/zenodo.3568418   0.1.0
```

I recall anything before `3.0.2` can be ditched - right?!
