### ISSUE TITLE
Loading austraits data is throwing strsplit bibtex error

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#8]
`library(austraits)
austraits`

$sources
Error in strsplit(tools:::BibTeX_entry_field_db[[bibtype]], "|", fixed = TRUE) : 
  non-character argument

Is this the R package's fault or the build? To be investigated

**Comment by dfalster** [comment]
Might require "RefManager" to be loaded. Does that change anything?

**Comment by fontikar** [comment]
Hooray!
