### ISSUE TITLE
`as_wide_table` cannot find columns that do not exist

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/austraits#83]
Currently `as_wide_table` will throw an error if any of the columns [here](https://github.com/traitecoevo/austraits/blob/c337e12b78ba3e7f0dccf8d5533d66ee646b534f/R/as_wide_table.R#L76) do not exist. I think `any_of(c(...))` should be added within the `select()` function so that any missing columns won't throw an error. This was happening when I built a dataset with NA latitudes and longitudes, but @ehwenk pointed out it will be relevant for other columns too with future changes to `build_update_taxonomy`, where only a few columns are required and the rest are optional. 

Also I think any time there is a `select` without `all_of(c()` or `any_of(c())` there will be tidyselect warning/note with R CMD check.

**Comment by dfalster** [comment]
We should review this together

**Comment by fontikar** [comment]
We will not fix this as there are other solutions for API usage (zendo download wide table) or use combine_table once it has been implemented
